name: My First Workflow

on: issues

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Message
        run: echo "Hello Fardeen! CI is working 🚀"

      - name: Print Date
        run: date
